# Generated by Django 6.0.3 on 2026-04-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.SlugField(help_text='ID único del hardware (ej: 16777215)', unique=True)),
                ('nombre_placa', models.CharField(help_text='Ej: Nodo Central Tablero', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Temperatura Habitación', max_length=100)),
                ('slug', models.SlugField(default='undefined', help_text='ID único (ej: temp_habitacion). No usar espacios.', max_length=100, unique=True)),
                ('pin_conexion', models.IntegerField(default=0, help_text='Pin GPIO usado en el microcontrolador', unique=True)),
                ('tipo', models.CharField(default='DHT11', max_length=50)),
                ('dispositivo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='sensores.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Temperatura', max_length=30)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
