# Generated by Django 6.0.3 on 2026-04-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': '1. Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='lectura',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lectura', 'verbose_name_plural': '3. Lecturas'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': '2. Sensores'},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Sala de Máquinas', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre_placa',
            field=models.CharField(help_text='Ej: Tablero Control Norte', max_length=100),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='sensores.dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nombre',
            field=models.CharField(help_text='Ej: Temperatura Motor', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pin_conexion',
            field=models.IntegerField(help_text='Pin GPIO (ej: 5 para D1)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='slug',
            field=models.SlugField(help_text='Identificador técnico (ej: temp_motor)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(default='DHT11', help_text='Ej: DHT22, PT100, NTC', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('dispositivo', 'pin_conexion'), name='unique_pin_per_device'),
        ),
    ]
