# Generated by Django 6.0.3 on 2026-04-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_alter_dispositivo_options_alter_lectura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='chip_id',
            field=models.SlugField(help_text='ID único del hardware (ej: MAC address o chip ID del fabricante)', unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre_placa',
            field=models.CharField(help_text='Nombre descriptivo para humanos (ej: Nodo Tanque Ácido)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física en planta (ej: Sector Lixiviación)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de recepción del dato (UTC-4 para Chile)'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='tipo',
            field=models.CharField(default='Temperatura', help_text='Unidad de medida (ej: Presión, Voltaje, Corriente)', max_length=30),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='valor',
            field=models.FloatField(help_text='Valor numérico de la medición'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nombre',
            field=models.CharField(help_text='Nombre del punto de medida (ej: Flujo Entrada)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pin_conexion',
            field=models.IntegerField(help_text='GPIO físico utilizado en el microcontrolador'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='slug',
            field=models.SlugField(help_text='ID técnico usado por el Dashboard (ej: flujo_ent)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(default='DHT11', help_text='Modelo del sensor (ej: DHT22, DS18B20, PT100)', max_length=50),
        ),
    ]
